values-zh-rCN/strings.xml
axel358/smartdock pull request #18
Opened 2023-02-18 08:42 UTC by 1457384613gh

values-zh-rCN/strings.xml

2023-02-18 11:23 UTC, utzcoz requested changes

2023-02-18 11:23 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think this file should be located to `app/src/main/res/values-zh-rCN/strings.xml`.

2023-02-18 12:02 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="running_apps_number_summary">此设置可以帮助屏幕较小的设备避免程序坞上的应用程序溢出</string>
溢出 -> 覆盖？or 显示异常？

2023-02-18 12:02 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="running_apps_number_title">显示正在运行/最近使用的应用数</string>
正在运行/最近使用的应用数量？

2023-02-18 12:02 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="none">None</string>
无？

2023-02-18 12:36 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="enable_nav_assist_title">启用『语音助手按钮』🎙️</string>
那是不是需要把按钮放到更外面呢？

2023-02-18 12:47 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="enable_nav_assist_title">启用『语音助手按钮』🎙️</string>
这样来说还是保留原样吧。

2023-02-18 12:57 UTC, utzcoz commented on app/src/main/values-zh-rCN/strings.xml
> +    <string name="wifi">WLAN</string>
I think it is a translation. You need to keep the pace with origin word. If you think `WLAN` is better than `WiFi`, you need to change origin `WiFi` to `WLAN` first.

2023-02-18 20:28 UTC, axel358 commented
@1457384613gh You can grab/build one from the Github Actions tab

2023-02-19 01:16 UTC, utzcoz reviewed
Thanks. Almost of it looks great. But I think there are something need to be polished.

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_ctrl_back_title">「右Ctrl键」作为『返回键』</string>
Add space for `Ctrl`?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_charge_complete_sound_title">设备结束充电后，播放自定义音频*</string>
Why there is a * at the end?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="a_launcher_for_android_x86_by_">由 Axel358 开发的，适用于安卓x86的桌面</string>
Add space for `x86`?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="k_s_maan_nblisslabs_project">K S Maan \nBliss Labs 合作的项目</string>
I think you need to keep `Bliss Labs project`.

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="smart_dock_its_free_and_open_">SmartDock\n时髦达客坞 \n它是开源并且免费的；在 GitHub 托管代码接受开源贡献</string>
What about keeping the origin English name for this app?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="menu">『App抽屉』</string>
Add space for `App`?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="num_columns_title">每排容纳 App图标的数量</string>
Add the space in the right of `App`?

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="allow_app_freeze_summary">您将需要一个外部工具来重新启用应用程序，例如『冰箱❄️』（或执行pm enable [pkgname]）</string>
I recommend to keep `Ice Box` instead of translating it to `冰箱`.

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +	<string name="accessibility_service_description">允许执行返回等操作</string>
Format

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="app_name">时髦达客坞</string>
I recommend to keep the origin app name.

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_qs_wifi_title">显示 WLAN图标</string>
Space for `WLAN`.

2023-02-19 01:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="contributors">贡献者👨‍💻</string>
I recommend to remove icon.

2023-02-19 02:01 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="a_launcher_for_android_x86_by_">由 Axel358 开发的，适用于安卓x86的桌面</string>
个人觉得 Android-x86 更合适， https://www.android-x86.org/。虽然很多文章都写“安卓x86”，但是我并不觉得这种写法一定正确。对于中英文混用情况一般推荐英文和旁边中文字符添加一个空格。

2023-02-19 02:02 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="allow_app_freeze_summary">您将需要一个外部工具来重新启用应用程序，例如『冰箱❄️』（或执行pm enable [pkgname]）</string>
如果这个应用有中文翻译名，那么把应用名称后面的 icon 去掉就行，毕竟有的人可能会直接复制去搜索应用，添加额外的 icon 会增加搜索难度。

2023-02-19 02:02 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_qs_wifi_title">显示 WLAN图标</string>
“显示 WLAN 图标”

2023-02-19 02:03 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="contributors">贡献者👨‍💻</string>
如果原先内容没有 icon，翻译的时候也没必要添加。

2023-02-19 02:14 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="app_name">时髦达客坞</string>
我觉得之前的名字就挺好的。比如 Taskbar 这个应用中文名还是 Taskbar，并没有改名字。

2023-02-19 02:15 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_ctrl_back_title">「右Ctrl键」作为『返回键』</string>
中英文混杂的情况是需要统一的。

2023-02-19 02:16 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="enable_charge_complete_sound_title">设备结束充电后，播放自定义音频*</string>
明白了，那保持原样就行了。

2023-02-19 02:20 UTC, utzcoz commented
> @axel358 @ilhan-athn7 @electrikjesus Could I add here an emoji of programmer? It will be so cute!
> 
> ![Screenshot_2023-02-19-10-10-15-372_com.github.android-edit.jpg](https://user-images.githubusercontent.com/69227436/219908407-e0b6040c-c888-4d90-bc54-11a8bb439dcd.jpg)

I think one of the rule of translating strings for different language is to keep the same and polish it with native language. If you want to add this icon/emoji,  you need to add it to the origin content.

2023-02-19 02:26 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="app_name">时髦达客坞</string>
I think SmartDock is too simple for discussion. Anyway, you can keep it you still want to give it a Chinese name for forks that don't want to use its simple English name. I just provide my suggestions for @axel358 's request.

2023-02-19 02:31 UTC, electrikjesus commented
I would agree with Utzcoz, it's not recommended to add differences in string translations unless it is a dialect or change in meaning (avoiding slang, etc). If you are proposing to add an emoji to the contributor string, then you will need to do it for all languages in order to be considered for review.

2023-02-19 08:22 UTC, utzcoz commented on app/src/main/res/values/strings.xml
> +    <string name="app_files_title">Files🗂️</string>
So you decide to add emojis for almost of origin English strings?

2023-02-19 08:36 UTC, utzcoz commented on app/src/main/res/values/strings.xml
> +    <string name="app_files_title">Files🗂️</string>
Actually, I recommend you to add Chinese translation at this PR only. And you can send a new PR to add emojis for existing strings because there are other language translations that you need to update together too.

2023-02-19 22:37 UTC, axel358 commented
@1457384613gh U might need to use another device like your phone for testing or completly remove Smart Dock previous version before installing

2023-02-20 10:01 UTC, axel358 commented
@1457384613gh I might have forgotten to extract those strings. I'll do it as soon as i can

2023-02-20 10:07 UTC, utzcoz commented on app/src/main/res/values-zh-rCN/strings.xml
>      <string name="enable_charge_complete_sound_title">设备结束充电后🔋，播放自定义音频*🔊</string>
Please don't use Chinese in commit title/message. Please keep to use English for commit title and message.

2023-02-22 09:54 UTC, axel358 commented
@1457384613gh Those strings are unused

2023-02-22 10:18 UTC, axel358 commented
@1457384613gh Ill do some cleanup when i have thr time, just ignore them

2023-02-26 11:24 UTC, utzcoz commented
@1457384613gh Looks like you modified XML files have incorrect format content.

2023-02-26 13:46 UTC, utzcoz commented on app/src/main/res/values/strings.xml
> -    <string name="tint_indicators_title">Tint running indicators</string>
I think it's not permitted to change English strings.xml format.

2023-02-26 13:46 UTC, utzcoz commented on app/src/main/res/values/strings.xml
> +					<<string name="soft_reboot_summary">Soft 🔄reboot now. You will lose all unsaved work</string>
It's obvious that there is an extra <.

2023-02-26 13:48 UTC, utzcoz commented
@1457384613gh It's recommended to let your PR as small as possible. Actually your later changes make your PR become more difficult to review, and it reduces the possibility of merging your PR.

2023-02-26 14:41 UTC, axel358 commented
@1457384613gh Please keep the structure of the original strings.xml as it is. I agree that grouping strings is a good idea but is making it harder for us to review and merge your PR. Please remove all the emojis. Just limit yourself to translating the original english strings withput adding any extras. Over the course of next week i'll ask @utzcoz to review this PR one last time. If there are still issues we'll have to close it

2023-02-26 14:43 UTC, axel358 commented
@1457384613gh In the future i might implement your idea of grouping strings.

2023-02-26 16:08 UTC, axel358 commented
@1457384613gh I extacted the missing strings and removed unused ones, thanks for pointing those out. About the emojis, Smart Dock is used by many different. What you might find cool others might find rude. That's why we gotta try to keep the language as polite and neutral as possible, so that everyone is happy :)

2025-07-03 13:15 UTC, closed without merging